<a href="https://colab.research.google.com/github/Mikolaj613/Kurs-Ai/blob/main/2_biblitokea_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python -- version

python3: can't open file '/content/version': [Errno 2] No such file or directory


In [2]:
!pip freeze | grep numpy

numpy==1.26.4


In [4]:
import numpy as np

#tworzenie tablicy
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array)
print(f"Kształt tablicy: {np.shape(array)}")

array2x6 = array.reshape(2,6)
print("Array 2x6")
print(array2x6)
print(f"Array 2x6 - kształt {np.shape(array2x6)}")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Kształt tablicy: (12,)
Array 2x6
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Array 2x6 - kształt (2, 6)


In [5]:

print(array)
print(f"Kształt tablicy: {np.shape(array)}")

array3x4 = array.reshape(3,4)
print("Array 3x4")
print(array3x4)
print(f"Array 3x4 - kształt {np.shape(array3x4)}")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Kształt tablicy: (12,)
Array 3x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array 3x4 - kształt (3, 4)


In [9]:
array2x2x3 = array.reshape(2,2,3)
print(array2x2x3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
unsorted1D = np.array([3,6,2,4])
print(unsorted1D)
sorted1D = np.sort(unsorted1D)
print(sorted1D)

[3 6 2 4]
[2 3 4 6]


In [11]:
unsorted2D = np.array([[7,2,9],
                       [4,8,1],
                       [5,6,3]])
print(unsorted2D)

sorted2D_axis0 = np.sort(unsorted2D,axis=0)
print(f"tablica posortowania oś 0:\n{sorted2D_axis0}")

sorted2D_axis1 = np.sort(unsorted2D,axis=1)
print(f"tablica posortowania oś 1:\n{sorted2D_axis1}")

[[7 2 9]
 [4 8 1]
 [5 6 3]]
tablica posortowania oś 0:
[[4 2 1]
 [5 6 3]
 [7 8 9]]
tablica posortowania oś 1:
[[2 7 9]
 [1 4 8]
 [3 5 6]]
